---
extends: default

rules:
  line-length:
    max: 160
    level: warning
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1

ignore: |
  .github/
  venv/
  ENV/
  env/
